# Generated by Django 5.0 on 2023-12-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('time_published', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('brief', models.TextField()),
                ('body', models.TextField()),
            ],
        ),
    ]
