# Generated by Django 5.0 on 2023-12-29 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='images/best2.jpg', upload_to='blog_images/'),
        ),
    ]
